version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build

  release:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Initialize git user
          command: |
            git config --global user.email "svc.authid-sdk-ci@twilio.com"
            git config --global user.name "authid-sdk-ci"
      - run:
          name: Setup git
          command: git branch --set-upstream-to=origin/main main
      - run:
          name: Authenticate with registry
          command: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Library
          command: npm run build
      - run:
          name: Release
          command: npm run release


workflows:
  test_sdk:
    jobs:
      - test
  build_sdk:
    jobs:
      - test
      - build:
          requires:
            - test
  release_sdk:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: main